apiVersion: v1
kind: Namespace
metadata:
  name: my-access-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-access-service-account
  namespace: my-access-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-access-role-binding
  namespace:  my-access-ns
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: my-access-service-account
  namespace:  my-access-ns