apiVersion: watson-aiops.ibm.com/v1beta1
kind: NOI
metadata:
  name: noi
  namespace: aiops
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  ldap:
    port: '389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '636'
    url: 'ldap://localhost:389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: ibmc-file-gold-gid
  backupRestore:
    enableAnalyticsBackups: false
  topology:
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    enabled: true
    netDisco: false
    observers:
      docker: false
      taddm: false
      servicenow: false
      ibmcloud: false
      alm: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: false
      itnm: false
      ansibleawx: false
      ciscoaci: false
      azure: false
      rancher: false
      newrelic: false
      vmvcenter: false
      rest: true
      appdynamics: false
      jenkins: false
      zabbix: false
      file: true
      googlecloud: false
      dynatrace: false
      aws: false
      openstack: false
      vmwarensx: false
    storageClassElasticTopology: ibmc-file-gold-gid
    storageClassFileObserver: ibmc-file-gold-gid
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
  version: 1.6.3
  entitlementSecret: cp.icr.io
  clusterDomain: >-
    ssss-4c84fa77-.us-south.containers.appdomain.cloud
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: ibmc-file-gold-gid
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: ibmc-file-gold-gid
    storageClassKafka: ibmc-file-gold-gid
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: ibmc-file-gold-gid
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: ibmc-file-gold-gid
    storageClassCouchdb: ibmc-file-gold-gid
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: ibmc-file-gold-gid
    storageSizeCassandraData: 50Gi
    storageClassDB2: ibmc-file-gold-gid
    storageClassElastic: ibmc-file-gold-gid
    storageSizeDB2: 5Gi
    storageClassImpactGUI: ibmc-file-gold-gid
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: ibmc-file-gold-gid
  deploymentType: trial
