apiVersion: v1
kind: ServiceAccount
metadata:
  name: runbook-service-account
  namespace: aiops21
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runbook-role-binding
  namespace:  aiops21
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: runbook-service-account
  namespace:  aiops21